image: Visual Studio 2017
configuration: Release
install:
  - choco install gitversion.portable --version 4.0.0-beta0012 --pre -y
  - ps: $env:Path = "C:\ProgramData\chocolatey\bin;$env:Path"
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /nofetch /b $env:APPVEYOR_REPO_BRANCH
  - ps: .\setVersion.ps1
nuget:
  account_feed: true
before_build:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
- cmd: appveyor-retry nuget restore
build:
  verbosity: minimal
build_script:
  - cmd: msbuild /p:Configuration=Release
  - cmd: msbuild /t:pack /p:Configuration=Release .\nuget\FleetCarma.VinServiceClient\FleetCarma.VinServiceClient.csproj
test:
  categories:
    except:
      - IntegrationTest
notifications:
- provider: Slack
  incoming_webhook:
    secure: iS94XrZk4Cp5RzE8U/jIsxGJZt5weVGFQjy1loyV6PXhfy3XdBkUbb5ZElwOi6vghgNynUpVhLeTh5FAEA1whMpnzcxF+SIMvTg+Mh437GY=
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true

for:
-
  branches:
    only:
      - master
  artifacts:
    path: '.\nuget\**\*.nupkg'
- 
  branches:
    except:
      - master